---

permissions: {}
on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  base:
    strategy:
      matrix:
        os: [ubuntu-latest]
      fail-fast: false
    name: "${{ matrix.os }}"
    runs-on: "${{ matrix.os }}"

    steps:
      - name: "Checkout sources"
        uses: actions/checkout@v4
      - name: "Cache shells"
        id: cache-shells
        uses: actions/cache@v4
        with:
          path: "cache/shells"
          key: "${{ runner.os }}-shells"
      - name: "Test scripts"
        shell: bash
        run: |
          # Testing scripts...
          shells_dir="./cache/shells"
          if test -e "${shells_dir:?}/bosh.tar.xz"; then
            : # Already downloaded
          else
            echo 'Downloading bosh...'
            mkdir -p -- "${shells_dir:?}" || exit $?
            wget -q -O "${shells_dir:?}/bosh.tar.xz" -- "http://fuz.su/pub/schilytools/bin/schily-2024-03-21-x86_64-linux-gcc.tar.xz" || exit $?
          fi
          mkdir -p -- "${shells_dir:?}/extracted/bosh" || exit $?
          tar -x -f "${shells_dir:?}/bosh.tar.xz" -C "${shells_dir:?}/extracted/bosh" || exit $?
          PATH="${PATH?}:${shells_dir:?}/extracted/bosh/opt/schily/bin" || exit $?
          #
          bosh --version || exit $?
          bosh -c 'echo 123' || exit $?
          #
          rm -f -r -- "${shells_dir:?}/extracted" || exit $?
